#include "lib.h"

#define PRENOTA 10 //INVIA I DATI PER LA PRENOTAZIONE AL CUP
#define CANCELLA_PRENOTAZIONE 11 //CANCELLA LA PRENOTAZIONE INVIATA AL CUP
#define INFO_PRENOTAZIONE 12 //RICEVE INFORMAZIONI RIGUARDANTI LA PRENOTAZIONE INVIATA AL CUP
#define LISTA_PRENOTAZIONI_UTENTE 13 //RICEVE LA LISTA DELLE PRENOTAZIONI ATTIVE


